# Generated by Django 5.1.3 on 2024-11-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_useraccount_password_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
